#!/bin/sh

find eir -name '*.txt' -print0 | xargs -0 -L1 ./extract-eir > eir.csv
find navigatela.lacity.org -name '*.txt' -print0 | xargs -0 -L1 ./extract-eir > ladot-wiltec.csv
find navigatela.lacity.org -name '*.txt' -print0 | xargs -0 ./extract-ladot > ladot.csv
