#!/usr/bin/perl -w

use strict;

my @line;

my $fname = $ARGV[0];
$fname =~ s/.*\///;

while (<>) {
	chomp;

	if (s/\014+//g) {
		push @line, "\014";
	}

	push @line, $_;
}

sub fixtime {
	my $time = $_[0];

	if ($time eq "815-815") {
		# systematic error in, e.g., 16971_SANWES100414
		$time = "815-930";
	}

	if ($time =~ /^(\d\d?)(\d\d)-(\d\d?)(\d\d)$/ ||
	    $time =~ /^(\d\d?):(\d\d)-(\d\d?):(\d\d)/) {
		my ($h1, $m1, $h2, $m2) = ($1, $2, $3, $4);

		if ($h1 < 7) {
			$h1 += 12;
		}
		if ($h2 < $h1) {
			$h2 += 12;
		}

		if (sprintf("%02d%02d", $h1, $m1) ge sprintf("%02d%02d", $h2, $m2)) {
			return "error $time $h1$m1 $h2$m2";
		}

		return sprintf("%02d:%02d-%02d:%02d", $h1, $m1, $h2, $m2);
	} else {
		return $time;
	}
}

sub col {
	my @text = @_;
	my @cols;
	my @fields;
	my $ns = "";
	my $ew = "";
	my $date = "";
	my $mode = "";
	my $off;
	my %mode = ();

	my $i;
	for ($i = 0; $i <= $#text; $i++) {
		if ($text[$i] =~ /AXLE CLASSIFICATION TURNING MOVEMENT COUNT/) {
			return;
		}
		if ($text[$i] =~ /24-HOUR ADT COUNT SUMMARY/) {
			return;
		}

		if ($text[$i] =~ /5-LEG/) {  # XXX
			return;
		}
		if ($text[$i] =~ /DIAGONAL CROSSWALK/) {  # XXX
			return;
		}

		if ($text[$i] =~ /INTERSECTION:.*N\/S *(.*)/) {
			$ns = $1;
			$ns =~ s/      .*//;
			$ns =~ s/,/ /g;
		}
		if ($text[$i] =~ /E\/W *(.*)/) {
			$ew = $1;
			$ew =~ s/      .*//;
			$ew =~ s/,/ /g;
		}
		if ($text[$i] =~ /DATE: *(.*)/) {
			$date = $1;
			$date =~ s/,//g;
		}

		if ($text[$i] =~ /NORTH *EAST *SOUTH *WEST *NORTH *EAST *SOUTH *WEST/) {
			$mode = "pedbike";
		}
		if ($text[$i] =~ /^PERIOD +LEG +LEG +LEG +LEG +LEG +LEG +LEG +LEG *$/) {
			$mode = "pedbike";
		}
		if ($text[$i] =~ /15 MIN COUNTS +NORTH +EAST +SOUTH +WEST +TOTAL +15 MIN COUNTS +NORTH +EAST +SOUTH +WEST +TOTAL/) {
			$mode = "pedbiketotal";
		}
		if ($text[$i] =~ /15 MIN COUNTS +LEG +LEG +LEG +LEG/) {
			$mode = "ped";
			$off = index($text[$i], "15 MIN");
			next;
		}

		if ($text[$i] =~ /^PERIOD +([NSEW]B[LRT][TH] +)+TOTAL/ ||
		    $text[$i] =~ /^TIME +([NSEW]B[LRT][TH] +)+TOTAL/ ||
		    $text[$i] =~ /^400-500 +([NSEW]B[LRT][TH] +)+TOTAL/) {
			$mode = "car";
			@cols = split(/ +/, $text[$i]);
			next;
		}

		if ($text[$i] =~ /^PERIOD( +[NSEW]B[LRT][TH])+ *$/) {
			# total column not labeled
			$mode = "car";
			@cols = split(/ +/, $text[$i]);
			push @cols, "TOTAL";
			next;
		}

		if ($text[$i] =~ /^$/) {
			$mode = "";
		}

		if ($text[$i] =~ /^[0-9]+-[0-9]+/) {
			@fields = split(/ +/, $text[$i]);

			if ($mode eq "pedbike") {
				if ($#fields == 8) {
					$fields[0] = fixtime($fields[0]);
					my $j;
					for ($j = 1; $j < 9; $j++) {
						if (defined($mode{"$fname,$ns / $ew,x,$date,$fields[0]"}[12 + $j - 1])) {
							die $text[$i];
						}

						$mode{"$fname,$ns / $ew,x,$date,$fields[0]"}[12 + $j - 1] = $fields[$j];
					}
				} else {
					# print "xxxx $mode $text[$i]\n";
				}
			} elsif ($mode eq "pedbiketotal") {
				if ($#fields == 11) {
					$fields[0] = fixtime($fields[0]);
					my $j;
					for ($j = 1; $j < 5; $j++) {
						if (defined($mode{"$fname,$ns / $ew,x,$date,$fields[0]"}[12 + $j - 1])) {
							die $text[$i];
						}
						$mode{"$fname,$ns / $ew,x,$date,$fields[0]"}[12 + $j - 1] = $fields[$j];
					}
					for ($j = 7; $j < 11; $j++) {
						if (defined($mode{"$fname,$ns / $ew,x,$date,$fields[0]"}[16 + $j - 7])) {
							die $text[$i];
						}
						$mode{"$fname,$ns / $ew,x,$date,$fields[0]"}[16 + $j - 7] = $fields[$j];
					}
				} else {
					# print "xxxx $mode $text[$i]\n";
				}
			} elsif ($mode eq "car") {
				my %sum = ();
				for ($a = 1; $a <= $#fields && $a <= $#cols; $a++) {
					unless ($fields[$a] =~ /^[0-9]+$/) {
						die $text[$i];
					}

					# print "$fields[$a] -> $cols[$a]\n";
					$sum{$cols[$a]} += $fields[$a];
					last if $cols[$a] eq "TOTAL";
				}

				$fields[0] = fixtime($fields[0]);
				my $off = 0;
				for my $dir ('SB', 'WB', 'NB', 'EB') {
					for my $turn ('RT', 'TH', 'LT') {
						my $key = "$dir$turn";

						if (defined($mode{"$fname,$ns / $ew,x,$date,$fields[0]"}[$off])) {
							print STDERR "$off was " . $mode{"$fname,$ns / $ew,x,$date,$fields[0]"}[$off] . "\n";
							die $text[$i];
						}

						if (!defined($sum{$key})) {
							# No N/S left turns at CAMDEN DRIVE/DAYTON DRIVE / WILSHIRE BOULEVARD
							$mode{"$fname,$ns / $ew,x,$date,$fields[0]"}[$off++] = "";
						} else {
							$mode{"$fname,$ns / $ew,x,$date,$fields[0]"}[$off++] = $sum{$key};
						}
					}
				}
			} else {
				# print "xxxxxx $text[$i]\n";
			}
		} elsif ($mode eq "ped") {
			@fields = split(/ +/, substr($text[$i], $off));
			next unless $fields[0] =~ /^[0-9]+-[0-9]+$/;
			$fields[0] = fixtime($fields[0]);
			for ($a = 1; $a < 5; $a++) {
				if (defined($mode{"$fname,$ns / $ew,x,$date,$fields[0]"}[12 + $a - 1])) {
					die $text[$i];
				}

				$mode{"$fname,$ns / $ew,x,$date,$fields[0]"}[12 + $a - 1] = $fields[$a];
			}
		}
	}

	# print "##### $ns / $ew, $date\n";

	for ($i = 0; $i <= $#text; $i++) {
		# print "$text[$i]\n";
	}

	my $m;
	for $m (sort(keys(%mode))) {
		print "$m,";

		my $j;
		for ($j = 0; $j < 20; $j++) {
			if (defined($mode{$m}[$j])) {
				print $mode{$m}[$j];
			}

			if ($j + 1 < 20) {
				print ",";
			}
		}

		print "\n";
	}
}

sub page {
	my @text = @_;

	my @cols = ();
	my $i;
	for ($i = 0; $i >= 0; $i = index($text[0], "WILTEC", $i + 1)) {
		push @cols, $i;
	}

	for ($i = 0; $i <= $#cols; $i++) {
		my @page = ();
		my $j;
		for ($j = 0; $j <= $#text; $j++) {
			if (length($text[$j]) <= $cols[$i]) {
				push @page, "";
			} elsif (defined($cols[$i + 1])) {
				push @page, substr($text[$j], $cols[$i], $cols[$i + 1]);
				$page[$#page] =~ s/ *$//;
			} else {
				push @page, substr($text[$j], $cols[$i]);
			}
		}

		col(@page);
	}
}

my $i;
for ($i = 0; $i <= $#line; $i++) {
	if ($line[$i] =~ /^WILTEC/) {
		my @text = ($line[$i]);

		for (my $j = $i + 1; $j <= $#line && $j < $i + 100; $j++) {
			last if $line[$j] =~ /WILTEC/;
			last if $line[$j] =~ /\014/;
			push @text, $line[$j];
		}

		page(@text);
	}
}
