#!/usr/bin/perl

use strict;

sub fixtime {
	my $time = $_[0];

	if ($time =~ /^(\d\d?)-(\d\d?)/) {
		my ($t1, $t2) = ($1, $2);

		if ($t1 < 7) {
			$t1 += 12;
		}
		if ($t2 < $t1) {
			$t2 += 12;
		}

		if (sprintf("%02d", $t1) ge sprintf("%02d", $t2)) {
			return "error $time $t1 $2";
		}

		return sprintf("%02d:00-%02d:00", $t1, $t2);
	} elsif ($time =~ /^(\d\d?):(\d\d)-(\d\d?):(\d\d)$/ ||
	         $time =~ /^(\d\d?)\.(\d\d?)-(\d\d?)\.(\d\d?)$/) {
		my ($h1, $m1, $h2, $m2) = ($1, $2, $3, $4);

		if ($h1 < 7) {
			$h1 += 12;
		}
		if ($h2 < $h1) {
			$h2 += 12;
		}
		if ($m1 == 3) {
			$m1 = 30;
		}
		if ($m2 == 3) {
			$m2 = 30;
		}

		if (sprintf("%02d%02d", $h1, $m1) ge sprintf("%02d%02d", $h2, $m2)) {
			return "error $time $h1$m1 $h2$m2";
		}

		return sprintf("%02d:%02d-%02d:%02d", $h1, $m1, $h2, $m2);
	}

	return $time;
}

while (1) {
	my $ns = "";
	my $ew = "";
	my $date = "";
	my $weather = "";
	my $leg = "";
	my $leg2 = "";
	my %movement = ();
	my @bikes = ();
	my $anything = 0;

	while (<>) {
		last if /^STREET/;
		last if /\014/;
	}

	while (<>) {
		s/\(Rev Apr 92\)//;
		s/Count by.*//;
		s/,/ /g;

		if (/^North\/South *(.*)/) {
			$ns = $1;
		}
		if (/^East\/West *(.*)/) {
			$ew = $1;
		}
		if (/Date: *(.*)Weather:(.*)/) {
			$date = $1;
			$weather = $2;
		}
		if (/^BIKES/) {
			@bikes = split(/ +/);
		}
		if (/^NORTHBOUND/) {
			$leg = "northbound";
			$leg2 = "southbound";
		}
		if (/^EASTBOUND/) {
			$leg = "eastbound";
			$leg2 = "westbound";
		}
		if (/^([0-9:.]+)-([0-9:.]+)/) {
			my @fields = split(/ +/);

			if ($#fields == 14) {
				chomp $fields[$#fields];
				$fields[0] = fixtime($fields[0]);

				if ($fields[1] != 0 || $fields[2] != 0 || $fields[3] != 0 ||
				    $fields[6] != 0 || $fields[7] != 0 || $fields[8] != 0 ||
				    $fields[11] != 0 || $fields[12] != 0 || $fields[13] != 0 || $fields[14] != 0) {
					if ($fields[4] != $fields[1] + $fields[2] + $fields[3] ||
					    $fields[9] != $fields[6] + $fields[7] + $fields[8] ||
					    $fields[10] != $fields[4] + $fields[9]) {
						# print "mismatched sum in $ARGV\n";
					} else {
						$movement{$fields[0]}{$leg}{"lt"} = $fields[1];
						$movement{$fields[0]}{$leg}{"th"} = $fields[2];
						$movement{$fields[0]}{$leg}{"rt"} = $fields[3];

						$movement{$fields[0]}{$leg2}{"lt"} = $fields[6];
						$movement{$fields[0]}{$leg2}{"th"} = $fields[7];
						$movement{$fields[0]}{$leg2}{"rt"} = $fields[8];

						$movement{$fields[0]}{$leg}{"p"} = sprintf("%d (%s %s)", $fields[11] + $fields[12], $fields[11], $fields[12]);
						$movement{$fields[0]}{$leg2}{"p"} = sprintf("%d (%s %s)", $fields[13] + $fields[14], $fields[13], $fields[14]);
					}
				}
			} elsif ($#fields == 13) {
				chomp $fields[$#fields];
				$fields[0] = fixtime($fields[0]);

				if ($fields[1] != 0 || $fields[2] != 0 || $fields[3] != 0 ||
				    $fields[5] != 0 || $fields[6] != 0 || $fields[7] != 0 ||
				    $fields[10] != 0 || $fields[11] != 0 || $fields[12] != 0 || $fields[13] != 0) {
					if ($fields[4] != $fields[1] + $fields[2] + $fields[3] ||
					    $fields[8] != $fields[5] + $fields[6] + $fields[7] ||
					    $fields[9] != $fields[3] + $fields[8]) {
						# print "mismatched sum in $ARGV\n";
					} else {
						$movement{$fields[0]}{$leg}{"lt"} = $fields[1];
						$movement{$fields[0]}{$leg}{"th"} = $fields[2];
						$movement{$fields[0]}{$leg}{"rt"} = $fields[3];

						$movement{$fields[0]}{$leg2}{"lt"} = $fields[5];
						$movement{$fields[0]}{$leg2}{"th"} = $fields[6];
						$movement{$fields[0]}{$leg2}{"rt"} = $fields[7];

						$movement{$fields[0]}{$leg}{"p"} = sprintf("%d (%s %s)", $fields[10] + $fields[11], $fields[10], $fields[11]);
						$movement{$fields[0]}{$leg2}{"p"} = sprintf("%d (%s %s)", $fields[12] + $fields[13], $fields[12], $fields[13]);
					}
				}
			}

			# print "$#fields $ARGV\n";
		}
		last if /\014/;
	}

	$ns =~ s/,/ /g;
	$ns =~ s/ +/ /g;
	$ns =~ s/ *$//g;
	$ew =~ s/,/ /g;
	$ew =~ s/ +/ /g;
	$ew =~ s/ *$//g;
	$date =~ s/ +/ /g;
	$date =~ s/ *$//g;
	$weather =~ s/ +/ /g;

	if ($ns ne "") {
		my $time;
		my $anyp = 0;

		for $time (keys(%movement)) {
			my $direction;
			for $direction ("southbound", "westbound", "northbound", "eastbound") {
				if ($movement{$time}{$direction}{'p'} != 0) {
					$anyp = 1;
				}
			}
		}
		if (!$anyp) {
			for $time (keys(%movement)) {
				my $direction;
				for $direction ("southbound", "westbound", "northbound", "eastbound") {
					$movement{$time}{$direction}{'p'} = "";
				}
			}
		}

		for $time (sort(keys(%movement))) {
			my $fn = $ARGV;

			print "$fn,$ns / $ew,x,$date,$time,";
			$anything = 1;

			my $direction;
			for $direction ("southbound", "westbound", "northbound", "eastbound") {
				my $turn;
				for $turn ("rt", "th", "lt") {
					print "$movement{$time}{$direction}{$turn},";
				}
			}

			for $direction ("southbound", "westbound", "northbound", "eastbound") {
				print "$movement{$time}{$direction}{'p'},";
			}

			print ",,,\n";
		}

		if (!$anything) {
			# print "nothing in $ARGV\n";
		}
	}

	last if $_ eq "";
}
