#!/usr/bin/perl

$foot = .00000274;
$pi = 4 * atan2(1, 1);

open(IN, "la-intersections");
while (<IN>) {
	chomp;
	($name, $lat, $lon) = split(/,/);
	$name =~ tr/a-z/A-Z/;
	$name =~ s/,//;

	$name =~ s/\bWEST\b/W/g;
	$name =~ s/\bEAST\b/E/g;
	$name =~ s/\bNORTH\b/N/g;
	$name =~ s/\bSOUTH\b/S/g;

	$name =~ s/^[NSEW] //;
	$name =~ s/\bAT [NSEW] /AT /;
	$name =~ s/\bAT\b/\//;

 	$name =~ s/\bROAD\b/RD/g;
	$name =~ s/\bLANE\b/LN/g;
	$name =~ s/\bSTREET\b/ST/g;
	$name =~ s/\bAVENUE\b/AVE/g;
	$name =~ s/\bBOULEVARD\b/BLVD/g;

	if ($lat{$name} ne "") {
		$latd = $lat{$name} - $lat;
		$lond = ($lon{$name} - $lon) * cos($lat{$name});
		$d = sqrt($latd * $latd + $lond * $lond);
		if ($d > 200 * $foot) {
			$dup{$name} = 1;
			next;
		}
	}

	$lat{$name} = $lat;
	$lon{$name} = $lon;
}
close(IN);

for $n (keys(%dup)) {
	$lat{$n} = "";
	$lon{$n} = "";
}

while (<>) {
	chomp;
	($id, $name, $rest) = split(/,/, $_, 3);

	next if $seen{$name};
	$seen{$name} = 1;

	$out = $_;
	$_ = $name;

	s/\015//;
	s/^[ \t]*//;
	s/&nbsp;//;
	chomp;

	tr/a-z/A-Z/;
	s/,//;

	s/\bWEST\b/W/g;
	s/\bEAST\b/E/g;
	s/\bNORTH\b/N/g;
	s/\bSOUTH\b/S/g;

	s/^[NSEW] //;
	s/\bAT [NSEW] /AT /;

	s/\bROAD\b/RD/g;
	s/\bLANE\b/LN/g;
	s/\bSTREET\b/ST/g;
	s/\bAVENUE\b/AVE/g;
	s/\bBOULEVARD\b/BLVD/g;

	if ($lat{$_} ne "") {
		print "$out,$lat{$_},$lon{$_}\n";
	} else {
		print "xxx $name\n";
	}
}
