#!/usr/bin/perl -w

use strict;

my @line;

while (<>) {
	chomp;

	if (s/\014+//) {
		push @line, "\014";
	}

	push @line, $_;
}

sub col {
	my @text = @_;
	my @cols;
	my @fields;
	my $ns = "";
	my $ew = "";
	my $date = "";
	my $mode = "";

	my $i;
	for ($i = 0; $i <= $#text; $i++) {
		if ($text[$i] =~ /INTERSECTION:.*N\/S *(.*)/) {
			$ns = $1;
			$ns =~ s/      .*//;
		}
		if ($text[$i] =~ /E\/W *(.*)/) {
			$ew = $1;
			$ew =~ s/      .*//;
		}
		if ($text[$i] =~ /DATE: *(.*)/) {
			$date = $1;
		}

		if ($text[$i] =~ /NORTH *EAST *SOUTH *WEST *NORTH *EAST *SOUTH *WEST/) {
			$mode = "pedbike";
		}

		if ($text[$i] =~ /^PERIOD +([NSEW]B[LRT][TH] +)+TOTAL/ ||
		    $text[$i] =~ /^TIME +([NSEW]B[LRT][TH] +)+TOTAL/ ||
		    $text[$i] =~ /^400-500 +([NSEW]B[LRT][TH] +)+TOTAL/) {
			$mode = "car";
			@cols = split(/ +/, $text[$i]);
			next;
		}

		if ($text[$i] =~ /^$/) {
			$mode = "";
		}

		if ($text[$i] =~ /^[0-9]+-[0-9]+/) {
			@fields = split(/ +/, $text[$i]);

			if ($mode eq "pedbike") {
				if ($#fields == 8) {
					print "1,$ns / $ew,$date,$fields[0],,,,,,,,,,,,,";
					my $j;
					for ($j = 1; $j < 9; $j++) {
						print "$fields[$j],";
					}
					print "\n";
				} else {
					print STDERR "??? $mode $text[$i]\n";
				}
			} elsif ($mode eq "car") {
				my %sum = ();
				for ($a = 1; $a <= $#fields && $a <= $#cols; $a++) {
					unless ($fields[$a] =~ /^[0-9]+$/) {
						die $text[$i];
					}

					# print "$fields[$a] -> $cols[$a]\n";
					$sum{$cols[$a]} += $fields[$a];
				}

				print "1,$ns / $ew,$date,$fields[0],";

				for my $dir ('SB', 'WB', 'NB', 'EB') {
					for my $turn ('RT', 'TH', 'LT') {
						my $key = "$dir$turn";
						print "$sum{$key},";
					}
				}

				print "\n";
			}
		}
	}

	print "##### $ns / $ew, $date\n";

	for ($i = 0; $i <= $#text; $i++) {
		print "$text[$i]\n";
	}
}

sub page {
	my @text = @_;

	my @cols = ();
	my $i;
	for ($i = 0; $i >= 0; $i = index($text[0], "WILTEC", $i + 1)) {
		push @cols, $i;
	}

	for ($i = 0; $i <= $#cols; $i++) {
		my @page = ();
		my $j;
		for ($j = 0; $j <= $#text; $j++) {
			if (length($text[$j]) <= $cols[$i]) {
				push @page, "";
			} elsif (defined($cols[$i + 1])) {
				push @page, substr($text[$j], $cols[$i], $cols[$i + 1]);
				$page[$#page] =~ s/ *$//;
			} else {
				push @page, substr($text[$j], $cols[$i]);
			}
		}

		col(@page);
	}
}

my $i;
for ($i = 0; $i <= $#line; $i++) {
	if ($line[$i] =~ /^WILTEC/) {
		my @text = ($line[$i]);

		for (my $j = $i + 1; $j <= $#line && $j < $i + 100; $j++) {
			last if $line[$j] =~ /WILTEC/;
			last if $line[$j] =~ /\014/;
			push @text, $line[$j];
		}

		page(@text);
	}
}
