#!/usr/bin/perl

$foot = .00000274;
$pi = 4 * atan2(1, 1);

open(IN, "la-intersections");
while (<IN>) {
	chomp;
	($name, $lat, $lon) = split(/,/);
	$name =~ s/at [NSEW] /at /;
	$name =~ tr/a-z/A-Z/;
	$name =~ s/^[NSEW] //;
	$name =~ s/\bROAD\b/RD/g;
	$name =~ s/\bLANE\b/LN/g;

	if ($lat{$name} ne "") {
		$latd = $lat{$name} - $lat;
		$lond = ($lon{$name} - $lon) * cos($lat{$name});
		$d = sqrt($latd * $latd + $lond * $lond);
		if ($d > 200 * $foot) {
			$dup{$name} = 1;
			next;
		}
	}

	$lat{$name} = $lat;
	$lon{$name} = $lon;
}
close(IN);

for $n (keys(%dup)) {
	$lat{$n} = "";
	$lon{$n} = "";
}

for $file (<reports/*.html>) {
	open (IN, "<$file");
	while (<IN>) {
		last if /<td class="tablerecord">/;
	}

	<IN>;
	$_ = <IN>;

	s/\015//;
	s/^[ \t]*//;
	s/&nbsp;//;
	tr/a-z/A-Z/;
	chomp;

	s/\bROAD\b/RD/g;
	s/\bLANE\b/LN/g;

	if (/[A-Za-z0-9]/) {
		print "$lat{$_},$lon{$_}, $_\n";
	} else {
		print STDERR "$file\n";
	}

	close(IN);
}
